onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/S
add wave -noupdate /testbench/Clk
add wave -noupdate /testbench/Reset
add wave -noupdate /testbench/Run
add wave -noupdate /testbench/Continue
add wave -noupdate /testbench/LED
add wave -noupdate /testbench/HEX0
add wave -noupdate /testbench/HEX1
add wave -noupdate /testbench/HEX2
add wave -noupdate /testbench/HEX3
add wave -noupdate /testbench/HEX4
add wave -noupdate /testbench/HEX5
add wave -noupdate /testbench/HEX6
add wave -noupdate /testbench/HEX7
add wave -noupdate /testbench/CE
add wave -noupdate /testbench/UB
add wave -noupdate /testbench/LB
add wave -noupdate /testbench/OE
add wave -noupdate /testbench/WE
add wave -noupdate /testbench/ADDR
add wave -noupdate /testbench/Data
add wave -noupdate /testbench/R0
add wave -noupdate /testbench/R1
add wave -noupdate /testbench/R2
add wave -noupdate /testbench/R3
add wave -noupdate /testbench/R4
add wave -noupdate /testbench/R5
add wave -noupdate /testbench/R6
add wave -noupdate /testbench/R7
add wave -noupdate /testbench/S
add wave -noupdate /testbench/Clk
add wave -noupdate /testbench/Reset
add wave -noupdate /testbench/Run
add wave -noupdate /testbench/Continue
add wave -noupdate /testbench/LED
add wave -noupdate /testbench/HEX0
add wave -noupdate /testbench/HEX1
add wave -noupdate /testbench/HEX2
add wave -noupdate /testbench/HEX3
add wave -noupdate /testbench/HEX4
add wave -noupdate /testbench/HEX5
add wave -noupdate /testbench/HEX6
add wave -noupdate /testbench/HEX7
add wave -noupdate /testbench/CE
add wave -noupdate /testbench/UB
add wave -noupdate /testbench/LB
add wave -noupdate /testbench/OE
add wave -noupdate /testbench/WE
add wave -noupdate /testbench/ADDR
add wave -noupdate /testbench/Data
add wave -noupdate /testbench/R0
add wave -noupdate /testbench/R1
add wave -noupdate /testbench/R2
add wave -noupdate /testbench/R3
add wave -noupdate /testbench/R4
add wave -noupdate /testbench/R5
add wave -noupdate /testbench/R6
add wave -noupdate /testbench/R7
add wave -noupdate /testbench/lc3/my_slc/d0/PC_REG/DataOut
add wave -noupdate /testbench/lc3/my_slc/d0/MAR_REG/DataOut
add wave -noupdate /testbench/lc3/my_slc/d0/MDR_REG/DataOut
add wave -noupdate /testbench/lc3/my_slc/d0/PC_REG/Reset
add wave -noupdate /testbench/lc3/my_slc/d0/PC_REG/Load
add wave -noupdate /testbench/lc3/my_slc/d0/PC_REG/DataIn
add wave -noupdate /testbench/lc3/my_slc/d0/IR_REG/Reset
add wave -noupdate /testbench/lc3/my_slc/d0/IR_REG/Load
add wave -noupdate /testbench/lc3/my_slc/d0/IR_REG/DataIn
add wave -noupdate /testbench/lc3/my_slc/d0/IR_REG/DataOut
add wave -noupdate /testbench/lc3/my_slc/d0/MAR_REG/Reset
add wave -noupdate /testbench/lc3/my_slc/d0/MAR_REG/Load
add wave -noupdate /testbench/lc3/my_slc/d0/MAR_REG/DataIn
add wave -noupdate /testbench/lc3/my_slc/d0/MDR_REG/Reset
add wave -noupdate /testbench/lc3/my_slc/d0/MDR_REG/Load
add wave -noupdate /testbench/lc3/my_slc/d0/MDR_REG/DataIn
add wave -noupdate /testbench/lc3/my_slc/d0/MDR_M/BUS
add wave -noupdate /testbench/lc3/my_slc/d0/MDR_M/MEM2IO
add wave -noupdate /testbench/lc3/my_slc/d0/MDR_M/Select
add wave -noupdate /testbench/lc3/my_slc/d0/MDR_M/Output
add wave -noupdate /testbench/lc3/my_slc/d0/GateALU
add wave -noupdate /testbench/lc3/my_slc/d0/GateMARMUX
add wave -noupdate /testbench/lc3/my_slc/d0/GateMDR
add wave -noupdate /testbench/lc3/my_slc/d0/GatePC
add wave -noupdate /testbench/lc3/my_slc/IR
add wave -noupdate /testbench/lc3/my_slc/MAR
add wave -noupdate /testbench/lc3/my_slc/MDR
add wave -noupdate /testbench/lc3/my_slc/PC
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {50000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 338
configure wave -valuecolwidth 104
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {241153 ps} {2092571 ps}
